### ISSUE TITLE
주제별로 코드 정리하기

### ISSUE THREAD

**Issue by eubnara** [eubnaraAlgorithmStudy/400617#5]
week7 같은 디렉토리를 그만 만들고, 주제별로 디렉토리를 생성하면 어떨까 합니다. 예를 들면, Dynamic Programming 과 같은 디렉토리를 만들고, 그 안에서는 README.md 파일에 어떤 문제를 풀 때마다(누구든) 목록에 추가하구요.

디렉토리 구조는 
 - 백준/알고스팟/어쩌구저쩌구
   - 문제번호(혹은 문제이름)_푼사람.cpp(.java, .py, .ruby ...) 

백준은 문제번호로 이름을 정하고 알고스팟은 문제이름으로 정하는 등, 각 사이트의 규칙에 맞게 정하는 건 어떨까 싶습니다. 어떤 문제에 대해서 여러사람의 코드를 비교하고 싶을 때, 각 사람의 디렉토리에 일일히 들어가는 건 귀찮지 않을까요?

@kiyoungSeong  @alpaholic  @HyunJunKwon  @YunJeon  @DongbinSeo  @Eunsooyoun

**Comment by eubnara** [comment]
- 요약: 주제별 / 사이트별 / 문제별 정리

**Comment by HyunJunKwon** [comment]
좋을 것 같슴돠~

**Comment by alpaholic** [comment]
괜찮넹~ 굿굿
